on: push
jobs:
  main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: npm install-ci-test
      - uses: actions/configure-pages@main
      - uses: actions/upload-pages-artifact@main
        with:
          path: ./build/static/
      - id: deployment
        uses: actions/deploy-pages@main
